exclude: |
  (?x)^(tests/data)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        name: ruff check
        alias: check
        args: [--fix]
      - id: ruff
        name: ruff check imports
        alias: check-imports
        args: [--fix, --select, I, --exit-non-zero-on-fix]
      - id: ruff-format
        name: ruff format
        alias: format
