name: Build and Create Draft Release

on:
  push:
    tags:
      - 'v*'

# Cancel in-progress runs when a new workflow with the same group is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-draft-release:
    runs-on: macos-latest
    permissions:
      contents: write
      discussions: write

    steps:
      - uses: actions/checkout@v5
      - uses: BradyAJohnston/setup-blender@v5
        with:
          version: 4.5

      - name: Build Extension
        run: |
          blender -b -P build.py

      - name: Create Draft Release
        run: |
          gh release create ${{ github.ref_name }} --draft --generate-notes *.zip
        env:
          GITHUB_TOKEN: ${{ github.token }}
